language: php

cache:
  directories:
    - $HOME/.composer/cache/files

# https://docs.travis-ci.com/user/build-stages

jobs:

  include:

    - stage: test

      php: 7.3

      before_script:
        - travis_retry composer self-update
        - travis_retry composer update --prefer-lowest --no-ansi --no-interaction --no-progress --no-scripts

      script:
        - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

# https://docs.travis-ci.com/user/notifications
notifications:
  email:
    on_success: never
    on_failure: always
